language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  repo: tract-health/tract-health.github.io
  target-branch: master
  verbose: true
on:
  branch: master
